<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="store"
    nsURI="store" nsPrefix="store">
  <eClassifiers xsi:type="ecore:EClass" name="Project">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasAuthorizedUsers" upperBound="-1"
        eType="#//User" eOpposite="#//User/hasRightsOn"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="concreteRevisions" upperBound="-1"
        eType="#//ConcreteRevision" eOpposite="#//ConcreteRevision/project"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="revisions" upperBound="-1"
        eType="#//Revision" eOpposite="#//Revision/project"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lastConcreteRevision" lowerBound="1"
        eType="#//ConcreteRevision"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lastRevision" eType="#//Revision"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="checkouts" upperBound="-1"
        eType="#//Checkout" eOpposite="#//Checkout/project"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//ObjectState"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="createdDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="createdBy" eType="#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="geoTag" eType="#//GeoTag"
        eOpposite="#//GeoTag/projects"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subProjects" upperBound="-1"
        eType="#//Project" eOpposite="#//Project/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Project"
        eOpposite="#//Project/subProjects"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clashDetectionSettings"
        eType="#//ClashDetectionSettings" eOpposite="#//ClashDetectionSettings/projects"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exportLengthMeasurePrefix"
        lowerBound="1" eType="#//SIPrefix" defaultValueLiteral="-3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="notinserviceinterface"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasRightsOn" upperBound="-1"
        eType="#//Project" eOpposite="#//Project/hasAuthorizedUsers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="revisions" upperBound="-1"
        eType="#//ConcreteRevision"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//ObjectState"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="createdOn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="createdBy" eType="#//User"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userType" eType="#//UserType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="username" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastSeen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Checkout">
    <eStructuralFeatures xsi:type="ecore:EReference" name="user" lowerBound="1" eType="#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="revision" lowerBound="1"
        eType="#//Revision" eOpposite="#//Revision/checkouts"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="project" lowerBound="1"
        eType="#//Project" eOpposite="#//Project/checkouts"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="checkin" eType="#//Revision"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="active" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ObjectState">
    <eLiterals name="ACTIVE"/>
    <eLiterals name="DELETED" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UserType">
    <eLiterals name="ADMIN"/>
    <eLiterals name="USER" value="1"/>
    <eLiterals name="ANONYMOUS" value="2" literal="ANONYMOUS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeoTag">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="projects" upperBound="-1"
        eType="#//Project" eOpposite="#//Project/geoTag"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="z" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="epsg" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="directionAngle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConcreteRevision">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="project" lowerBound="1"
        eType="#//Project" eOpposite="#//Project/concreteRevisions"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//CheckinState"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="checksum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="revisions" upperBound="-1"
        eType="#//Revision" eOpposite="#//Revision/concreteRevisions"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastError" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Revision">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="user" lowerBound="1" eType="#//User"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="concreteRevisions" upperBound="-1"
        eType="#//ConcreteRevision" eOpposite="#//ConcreteRevision/revisions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lastConcreteRevision" eType="#//ConcreteRevision"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="checkouts" upperBound="-1"
        eType="#//Checkout" eOpposite="#//Checkout/revision"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="project" lowerBound="1"
        eType="#//Project" eOpposite="#//Project/revisions"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//CheckinState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lastClashes" upperBound="-1"
        eType="#//Clash"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tag" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastError" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GuidClash" eSuperTypes="#//Clash">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="guid1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="guid2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClashDetectionSettings">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="projects" upperBound="-1"
        eType="#//Project" eOpposite="#//Project/clashDetectionSettings"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="margin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="revisions" upperBound="-1"
        eType="#//Revision"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ignoredClasses" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SIPrefix">
    <eLiterals name="meter" literal="NULL"/>
    <eLiterals name="attometer" value="-18" literal="ATTO"/>
    <eLiterals name="femtometer" value="-15" literal="FEMTO"/>
    <eLiterals name="picometer" value="-12" literal="PICO"/>
    <eLiterals name="nanometer" value="-9" literal="NANO"/>
    <eLiterals name="micrometer" value="-6" literal="MICRO"/>
    <eLiterals name="millimeter" value="-3" literal="MILLI"/>
    <eLiterals name="centimeter" value="-2" literal="CENTI"/>
    <eLiterals name="decimeter" value="-1" literal="DECI"/>
    <eLiterals name="decameter" value="1" literal="DECA"/>
    <eLiterals name="hectometer" value="2" literal="HECTO"/>
    <eLiterals name="kilometer" value="3" literal="KILO"/>
    <eLiterals name="megameter" value="6" literal="MEGA"/>
    <eLiterals name="gigameter" value="9" literal="GIGA"/>
    <eLiterals name="terameter" value="12" literal="TERA"/>
    <eLiterals name="petameter" value="15" literal="PETA"/>
    <eLiterals name="exameter" value="18" literal="EXA"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Clash">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="revision1" eType="#//Revision"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="revision2" eType="#//Revision"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EidClash" eSuperTypes="#//Clash">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eid1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eid2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CheckinState">
    <eLiterals name="UPLOADING"/>
    <eLiterals name="PARSING" value="1"/>
    <eLiterals name="STORING" value="2"/>
    <eLiterals name="SEARCHING_CLASHES" value="3"/>
    <eLiterals name="DONE" value="4"/>
    <eLiterals name="ERROR" value="5"/>
    <eLiterals name="CLASHES_ERROR" value="6" literal="CLASHES_ERROR"/>
  </eClassifiers>
  <eSubpackages name="log" nsURI="log" nsPrefix="log">
    <eClassifiers xsi:type="ecore:EClass" name="ServerLog">
      <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
          eType="#//log/LogAction"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LogAction">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="executor" eType="#//User"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessMethod" eType="#//log/AccessMethod"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NewUserAdded" eSuperTypes="#//log/LogAction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="user" eType="#//User"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NewProjectAdded" eSuperTypes="#//log/LogAction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="project" eType="#//Project"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NewRevisionAdded" eSuperTypes="#//log/LogAction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="revision" eType="#//Revision"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NewCheckoutAdded" eSuperTypes="#//log/LogAction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="checkout" eType="#//Checkout"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SettingsSaved" eSuperTypes="#//log/LogAction"/>
    <eClassifiers xsi:type="ecore:EClass" name="UserAddedToProject" eSuperTypes="#//log/LogAction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="user" eType="#//User"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="project" eType="#//Project"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NewIgnoreFileUploaded" eSuperTypes="#//log/LogAction"/>
    <eClassifiers xsi:type="ecore:EClass" name="Download" eSuperTypes="#//log/LogAction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="revision" eType="#//Revision"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="zipped" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="AccessMethod">
      <eLiterals name="SOAP"/>
      <eLiterals name="WEB_INTERFACE" value="1"/>
      <eLiterals name="INTERNAL" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UserRemovedFromProject" eSuperTypes="#//log/LogAction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="user" eType="#//User"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="project" eType="#//Project"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProjectDeleted" eSuperTypes="#//log/LogAction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="project" eType="#//Project"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UserDeleted" eSuperTypes="#//log/LogAction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="user" eType="#//User"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PasswordReset" eSuperTypes="#//log/LogAction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="user" eType="#//User"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DatabaseCreated" eSuperTypes="#//log/LogAction"/>
    <eClassifiers xsi:type="ecore:EClass" name="ServerStarted" eSuperTypes="#//log/LogAction"/>
    <eClassifiers xsi:type="ecore:EClass" name="ProjectUpdated" eSuperTypes="#//log/LogAction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="project" eType="#//Project"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UserUndeleted" eSuperTypes="#//log/LogAction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="user" eType="#//User"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProjectUndeleted" eSuperTypes="#//log/LogAction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="project" eType="#//Project"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
